apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: filebrowser
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: frontend
status:
  loadBalancer: {}